export const solarProTheme = {
  colors: {
    background: '#F4F7FC',
    card: '#FFFFFF',
    border: '#DCE4F2',
    inputBg: '#F8FAFF',
    inputBorder: '#CBD7EE',
    textPrimary: '#0F172A',
    textSecondary: '#334155',
    textMuted: '#64748B',
    primary: '#2563EB',
    primaryDark: '#1D4ED8',
    successBg: '#ECFDF3',
    successBorder: '#A7F3D0',
    successText: '#047857',
    errorBg: '#FEF2F2',
    errorBorder: '#FECACA',
    errorText: '#B91C1C',
    white: '#FFFFFF',
  },
};
